[FE] 아카이빙 msw 연동 및 custom hook 구현
softeerbootcamp-2nd/H9-88Hey pull request #149
Opened 2023-08-17 05:58 UTC by kim-limit

# 📌 TO-DO
- 아카이빙 api 명세에 따라 msw로 구현
- 무한스크롤 로직 custom hook으로 구현
- Masonry layout custom hook 으로 구현

# 🔍 논의하고 싶은 내용

# 🏷️ 기타 사항

Closes #135

2023-08-17 07:31 UTC, lee-yun-pyo approved these changes
수고하셨습니다~

2023-08-18 02:41 UTC, sukam09 requested changes
코드가 잘 읽히고 전반적으로 아주 좋습니다~ 코멘트만 한번 확인해주세요!

2023-08-18 02:41 UTC, sukam09 commented on frontend/src/hooks/useCache.ts
> +  const { cachedDatas } = useContext(CacheContext);
should: data에는 s를 붙이지 않아요 만약 배열이라면 dataList와 같이 써 주세요!

2023-08-18 02:41 UTC, sukam09 commented on frontend/src/hooks/useFetchSuspense.ts
> +  fetchOptions?: object;
should: 무슨 object인지 interface로 보여주는게 더 좋지 않을까요?

2023-08-18 02:41 UTC, sukam09 commented on frontend/src/hooks/useFetchSuspense.ts
> +  staleTIme: number;
should: 오타 발견~ staleTime으로 수정해주세용

2023-08-18 02:41 UTC, sukam09 commented on frontend/src/hooks/useInfiniteFetch.ts
> +      }
may: !data라고 안쓴거 very good!

2023-08-18 02:41 UTC, sukam09 commented on frontend/src/hooks/useMasonryLayout.ts
> +    const element = item as HTMLElement;
may: as를 쓰려고 변수명을 바꾼 건가요?🤔

2023-08-18 02:41 UTC, sukam09 commented on frontend/src/components/Archiving/OptionList/index.tsx
> +  }, [options]);
must: 커스텀 훅을 useEffect 내에서 쓸 수가 있나요?

2023-08-18 02:41 UTC, sukam09 commented on frontend/src/components/Archiving/ReviewList/index.tsx
> +    useMasonryLayout({ element: masonryRef });
must: 여기도 한번 확인 부탁드려요!

2023-08-18 04:30 UTC, sukam09 approved these changes

2023-08-18 04:31 UTC, merged