[FE] 무한 스크롤 스크롤 버튼 및 렌더링 최적화
softeerbootcamp-2nd/H9-88Hey pull request #207
Opened 2023-08-22 07:16 UTC by kim-limit

# 📌 TO-DO
- 무한 스크롤 스크롤 버튼 구현
- 불필요한 렌더링 방지

# 🔍 논의하고 싶은 내용

# 🏷️ 기타 사항

Close #205

2023-08-22 07:33 UTC, lee-yun-pyo approved these changes
오우 고생하셨습니다!

2023-08-22 07:33 UTC, lee-yun-pyo commented on frontend/src/pages/Archiving/index.tsx
> +import { ScrollTopButton } from '@/components/common/ScrollTopButton';
개행 부탁들여요!

2023-08-22 07:33 UTC, lee-yun-pyo commented on frontend/src/hooks/useShowScrollButton.ts
> +  };
arrow function이 있네요

2023-08-22 08:03 UTC, kim-limit commented on frontend/src/hooks/useShowScrollButton.ts
> +  };
헉 수정했습니다...!

2023-08-23 09:09 UTC, sukam09 requested changes
렌더링 최적화 수고 많으셨습니다~ 되게 중요하게 생각하는 부분인데 저희 프로젝트에서 시도해봐서 너무 다행이라고 생각합니다😊 코멘트만 한번 확인해주세여~

2023-08-23 09:09 UTC, sukam09 commented on frontend/src/pages/Option/index.tsx
> +      ...currentSubOption,
may: 👍

2023-08-23 09:09 UTC, sukam09 commented on frontend/src/pages/Trim/BodyType/index.tsx
> +  const initialIndex = index !== -1 ? index : 0;
should: 여기도 initialIndex를 -1로 한 이유가 있나요?

2023-08-23 09:09 UTC, sukam09 commented on frontend/src/pages/Trim/BodyType/index.tsx
> +              onSetIndex={handleSetIndex(index)}
should: 이거 제가 잘 몰라서 그러는데 onSetIndex={index => handleSetIndex(index)}와 같이 쓰지도 않아도 되는 건가요?

2023-08-23 12:58 UTC, kim-limit commented on frontend/src/pages/Color/index.tsx
> +  const InteriorInitialIndex = interiorIndex !== -1 ? interiorIndex : 0;
저게 색상 페이지 들어왔을때 전역값에 들어있는 선택된 색상으로 index state init하는 로직 윤표님이 짜놓으셨는데 suspense 적용전에 useEffect에 있어서 깜박거리는 문제 있었는데 suspense fetch 적용후에 useEffect 전에 로직 계산 가능해서 위로 올렸습니다!

2023-08-23 13:00 UTC, kim-limit commented on frontend/src/pages/Trim/BodyType/index.tsx
> +  const initialIndex = index !== -1 ? index : 0;
진짜 만약에 전역에서 내려준 값이 현재 화면에 보여줘야하는 값중에 없다면 findIndex 하면 -1이 나오게 되니까 안전하게 처리하려고 했습니다!

2023-08-23 13:01 UTC, kim-limit commented on frontend/src/pages/Trim/BodyType/index.tsx
> +              onSetIndex={handleSetIndex(index)}
훅 내부가 커링으로 구현되어있어서 저렇게 사용가능합니다!

2023-08-23 14:03 UTC, sukam09 commented on frontend/src/pages/Option/index.tsx
> +  }
아 제가 깜빡했네요 ㅠㅠ 알겠습니다!

2023-08-23 14:03 UTC, sukam09 approved these changes

2023-08-23 14:04 UTC, merged