[FE] 색상 선택 페이지 마무리
softeerbootcamp-2nd/H9-88Hey pull request #70
Opened 2023-08-10 03:56 UTC by lee-yun-pyo

# 📌 TO-DO
 - 색상 페이지 UI 수정
 - Footer에 데이터 적용
 - msw fetch 사용

# 🔍 논의하고 싶은 내용

# 🏷️ 기타 사항
Close #52

2023-08-10 04:27 UTC, kim-limit commented on frontend/src/components/common/Footer/index.tsx
> +            <style.ColorCircle imageUrl={outerColor.imageUrl || undefined} />
여기 위에서 undefined 말고 ''로 넣어주면 더 좋을거 같아요

2023-08-10 04:28 UTC, kim-limit commented on frontend/src/components/common/Footer/style.tsx
>  `;
그럼 여기서 imageUrl: string으로 해주고 불필요한 조건 뺼 수 있을거 같아요!

2023-08-10 04:28 UTC, kim-limit commented on frontend/src/components/color/ExternalCarImage/index.tsx
> +  function goPrevImage() {
핸들러 앞에는 Handle 붙이는게 더 직관적이라 좋아요!

2023-08-10 04:29 UTC, kim-limit reviewed
고생했어요~~

2023-08-10 06:49 UTC, sukam09 requested changes
색상 페이지 마무리하느라 수고 많으셨습니다! 😊
코멘트만 한번씩 확인해주세요

2023-08-10 06:49 UTC, sukam09 commented on frontend/src/components/color/ExternalCarImage/index.tsx
> +  }
오 이거 잘했어요! 굿굿👍

2023-08-10 06:49 UTC, sukam09 commented on frontend/src/components/layout/MyCarLayout/index.tsx
> +  innerColor: { title: '', imageUrl: '', id: 1 },
should: 여기 id와 price는 왜 들어갔나요?

2023-08-10 06:49 UTC, sukam09 commented on frontend/src/components/layout/MyCarLayout/index.tsx
> +  }
should: price랑 id 그냥 price: price가 아니고 price 이런 식으로 한번만 쓸 수 있어요!

2023-08-10 06:49 UTC, sukam09 commented on frontend/src/pages/Color/index.tsx
> +    colorImageURL: innerImageUrl,
must: 저희 컨벤션 바뀌어서 API parameter도 모두 URL이 아니라 Url로 바꿔주셔야 해요 ㅜㅜ

2023-08-10 06:49 UTC, sukam09 commented on frontend/src/pages/Color/index.tsx
> +      price: data.exterierColors[index].additionalPrice,
should: data.exterierColors[index]가 겹치니깐 별도의 변수로 빼는건 어떨까요?

2023-08-10 06:49 UTC, sukam09 commented on frontend/src/pages/Color/index.tsx
> +      id: list[index].id,
should: 위와 마찬가지로 변수로 빼면 좋을것 같아요

2023-08-10 07:04 UTC, lee-yun-pyo commented on frontend/src/components/layout/MyCarLayout/index.tsx
> +  innerColor: { title: '', imageUrl: '', id: 1 },
price는 외부 색상 중 추가 가격이 있는 색상이 있는데 그 색상을 선택하면 총 가격에 포함시키려고 한 겁니다.
id는 외부색상마다 가능한 내부색상이 다른데 이용가능한 내부색상 리스트를 확인하려고 하는 겁니다.

2023-08-10 07:04 UTC, lee-yun-pyo commented on frontend/src/components/layout/MyCarLayout/index.tsx
> +  }
네 고칠게여

2023-08-10 07:10 UTC, lee-yun-pyo commented on frontend/src/pages/Color/index.tsx
> +      price: data.exterierColors[index].additionalPrice,
오 좋아여 수정할게요 밑에도요~

2023-08-10 07:27 UTC, lee-yun-pyo commented on frontend/src/pages/Color/index.tsx
> +    colorImageURL: innerImageUrl,
바꿨습니다!

2023-08-10 07:27 UTC, lee-yun-pyo commented on frontend/src/components/common/Footer/index.tsx
> +            <style.ColorCircle imageUrl={outerColor.imageUrl || undefined} />
네!

2023-08-10 07:32 UTC, sukam09 approved these changes

2023-08-10 07:54 UTC, kim-limit approved these changes
고생하셨습니다~~ 굳굳이여

2023-08-10 07:54 UTC, merged

2023-08-11 07:21 UTC, devMingu commented on frontend/src/components/common/Footer/index.tsx
> +            <style.ColorCircle imageUrl={outerColor.imageUrl || undefined} />
옵셔널체이닝 사용해보는것도 좋을것 같아요! `outerColor?.imageUrl`